# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: hpi-swa/setup-smalltalkCI@v1
        id: smalltalkci
        with:
          smalltalk-image: 'Pharo64-9.0'
      - run: smalltalkci -s ${{ steps.smalltalkci.outputs.smalltalk-image }}
        shell: bash
        timeout-minutes: 15
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          # Artifact name
          name: build
          # A file, directory or wildcard pattern that describes what to upload
          path: HTML/JSUBNameGenerator/UBNameGeneratorApp/
          # The desired behavior if no files are found using the provided path.
          
      - name: Copy files to another repository
  # You may pin to the exact commit or the version.
  # uses: nkoppel/push-files-to-another-repository@993c4b2dae204519735dd914c24dd6f1d2acd24d
        uses: nkoppel/push-files-to-another-repository@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
    # The files/directories to copy to the destination repository. Can have multiple space-separated filenames and globbing.
          source-files:  HTML/JSUBNameGenerator/UBNameGeneratorApp/index.html HTML/JSUBNameGenerator/UBNameGeneratorApp/index.js
    # Name of the destination username/organization
          destination-username: mattonem
    # Name of the destination repository
          destination-repository: mattonem.github.io
    # [Opitonal] Directory to copy files into in the destination repository
          destination-directory: ./ubuntuNameGenerator
    # [Optional] Username for the commit. Defaults to the destination username
          commit-username: maxmattone
    # Email for the commit
          commit-email: mattonem@gmail.com
    # [Optional] commit message for the output repository. ORIGIN_COMMIT is replaced by the URL@commit in the origin repo
          commit-message: 'update '
